version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: 1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

